//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stoktakibiproje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsatislar
    {
        public int satisid { get; set; }
        public Nullable<int> urunid { get; set; }
        public Nullable<int> musteriid { get; set; }
        public Nullable<int> adet { get; set; }
        public Nullable<decimal> fiyat { get; set; }
    
        public virtual tblmusteriler tblmusteriler { get; set; }
        public virtual tblurunler tblurunler { get; set; }
    }
}
